name: Build

on:
  push:
    branches-ignore: [translation]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with DevkitARM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup environment
        run: git config --global safe.directory '*'
      - name: Install tools
        run: |
          sudo apt-get update
      - name: Build
        id: build
        run: |
          make
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v4
        with:
          path: /__w/3dsdl/3dsdl/*
          name: build
